<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            ['name' => 'admin.user.create'],
            ['name' => 'admin.user.edit'],
            ['name' => 'admin.user.index'],
            ['name' => 'admin.user.reactivate'],
            ['name' => 'admin.user.deactivate'],
            ['name' => 'admin.role.index'],
            ['name' => 'admin.role.create'],
            ['name' => 'admin.role.edit'],
            ['name' => 'admin.role.delete'],
            ['name' => 'admin.client.create'],
            ['name' => 'admin.client.edit'],
            ['name' => 'admin.client.index'],
            ['name' => 'admin.client.delete'],
            ['name' => 'admin.profession.index'],
            ['name' => 'admin.profession.create'],
            ['name' => 'admin.profession.edit'],
            ['name' => 'admin.profession.delete'],
            ['name' => 'admin.account-code.index'],
            ['name' => 'admin.account-code.create'],
            ['name' => 'admin.account-code.edit'],
            ['name' => 'admin.account-code.delete'],
            ['name' => 'admin.account-code.sub-category.create'],
            ['name' => 'admin.account-code.additional-category.create'],
            ['name' => 'admin.master-chart.index'],
            ['name' => 'admin.master-chart.create'],
            ['name' => 'admin.master-chart.edit'],
            ['name' => 'admin.master-chart.delete'],
            ['name' => 'admin.master-chart.sub-category.create'],
            ['name' => 'admin.master-chart.additional-category.create'],
            ['name' => 'admin.service.index'],
            ['name' => 'admin.service.create'],
            ['name' => 'admin.service.edit'],
            ['name' => 'admin.service.delete'],
            ['name' => 'admin.master-chart.additional-category.delete'],
            ['name' => 'admin.bs_import.index'],
            ['name' => 'admin.bs_import.create'],
            ['name' => 'admin.bs_import.edit'],
            ['name' => 'admin.bs_import.bs_import'],
            ['name' => 'admin.bs_input.index'],
            ['name' => 'admin.bs_input.create'],
            ['name' => 'admin.bs_input.edit'],
            ['name' => 'admin.bs_input.post'],
            ['name' => 'admin.period.sh'],
            ['name' => 'admin.period.client_pro'],
            ['name' => 'admin.verify_account.index'],
            ['name' => 'admin.period_lock.index'],
            ['name' => 'admin.journal_entry.index'],
            ['name' => 'admin.journal_entry.create'],
            ['name' => 'admin.journal_entry.edit'],
            ['name' => 'admin.journal_entry.delete'],
            ['name' => 'admin.depreciation.index'],
            ['name' => 'admin.depreciation.edit'],
            ['name' => 'admin.depreciation.create'],
            ['name' => 'admin.depreciation.delete'],
            ['name' => 'admin.manage_invest.index'],
            ['name' => 'admin.manage_invest.edit'],
            ['name' => 'admin.manage_invest.create'],
            ['name' => 'admin.manage_invest.delete'],
            ['name' => 'admin.budget.index'],
            ['name' => 'admin.budget.edit'],
            ['name' => 'admin.budget.create'],
            ['name' => 'admin.budget.delete'],
            ['name' => 'admin.period.index'],
            ['name' => 'admin.period.edit'],
            ['name' => 'admin.period.create'],
            ['name' => 'admin.period.delete'],
            ['name' => 'admin.client_payment.index'],
            ['name' => 'admin.client_payment.edit'],
            ['name' => 'admin.client_payment.create'],
            ['name' => 'admin.client_payment.delete'],
            ['name' => 'admin.fuel_tax_cr.index'],
            ['name' => 'admin.fuel_tax_cr.edit'],
            ['name' => 'admin.fuel_tax_cr.create'],
            ['name' => 'admin.fuel_tax_cr.delete'],
            ['name' => 'admin.coefficients.index'],
            ['name' => 'admin.coefficients.edit'],
            ['name' => 'admin.coefficients.create'],
            ['name' => 'admin.coefficients.delete'],
            ['name' => 'admin.i_tax_table.index'],
            ['name' => 'admin.i_tax_table.edit'],
            ['name' => 'admin.i_tax_table.create'],
            ['name' => 'admin.i_tax_table.delete'],
            ['name' => 'admin.wages.index'],
            ['name' => 'admin.wages.edit'],
            ['name' => 'admin.wages.create'],
            ['name' => 'admin.wages.delete'],
            ['name' => 'admin.superannuation.index'],
            ['name' => 'admin.superannuation.edit'],
            ['name' => 'admin.superannuation.create'],
            ['name' => 'admin.superannuation.delete'],
            ['name' => 'admin.leave.index'],
            ['name' => 'admin.leave.edit'],
            ['name' => 'admin.leave.create'],
            ['name' => 'admin.leave.delete'],
            ['name' => 'admin.deducation.index'],
            ['name' => 'admin.deducation.edit'],
            ['name' => 'admin.deducation.create'],
            ['name' => 'admin.deducation.delete'],
            ['name' => 'admin.close_year.index'],
            ['name' => 'admin.close_year.edit'],
            ['name' => 'admin.close_year.create'],
            ['name' => 'admin.close_year.delete'],
            ['name' => 'admin.cash_basis.index'],
            ['name' => 'admin.accrued_basis.index'],
            ['name' => 'admin.periodic_cash.index'],
            ['name' => 'admin.periodic_accrued.index'],
            ['name' => 'admin.general_ledger.index'],
            ['name' => 'admin.trial_balance.index'],
            ['name' => 'admin.profit_loss_excl.index'],
            ['name' => 'admin.profit_loss_incl.index'],
            ['name' => 'admin.balance_sheet.index'],
            ['name' => 'admin.comperative_bs.index'],
            ['name' => 'admin.complete_financial_report.index'],
            ['name' => 'admin.comperative_financial_report.index'],
            ['name' => 'admin.advanced_report.index'],
            ['name' => 'admin.depreciation_report.index'],
            ['name' => 'admin.consolidated_report.index'],
            ['name' => 'admin.investment_report.index'],
            ['name' => 'admin.ratio_report.index'],
            ['name' => 'admin.financial_analysis.index'],
            ['name' => 'admin.database_dump.index'],
            ['name' => 'admin.agent_audit.index'],
            ['name' => 'admin.logging_audit.index'],
            ['name' => 'admin.visitor_info.index'],
        ];

        foreach ($permissions as &$permission) {
            $permission['guard_name'] = 'admin';
        }

        \Spatie\Permission\Models\Permission::insert($permissions);
    }
}
